go: add dependents to metrics
AlexTereshenkov/dg-query pull request #13
Opened 2024-09-22 00:19 UTC by AlexTereshenkov

```
$ go run main.go metrics --dg="examples/dg-real-transitive.json" --metric=deps-transitive | jq                                                                     
{
  "deps-transitive": {
    "foo-dep1-dep1.py": 0,
    "foo-dep1-dep2.py": 0,
    "foo-dep1.py": 2,
    "foo-dep2.py": 0,
    "foo.py": 4,
    "spam-dep1.py": 0,
    "spam-dep2-dep1.py": 0,
    "spam-dep2-dep2.py": 0,
    "spam-dep2.py": 2,
    "spam.py": 4
  }
```

2024-09-26 21:29 UTC, ekhabarov requested changes

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
> +Get direct dependencies given adjacency list (used both for dependencies and dependents)
Comments [should start ](https://go.dev/wiki/CodeReviewComments#comment-sentences) with a function name.

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
> +Get transitive dependencies given adjacency list (used both for dependencies and dependents)
Comments [should start ](https://go.dev/wiki/CodeReviewComments#comment-sentences)with a function name.

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
> +	depsCount := make(GenericMapStringToAny)
nit: 
```suggestion
	depsCount := &GenericMapStringToAny{}
```

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
> +func metrics(filePathDg string, filePathDgReverse string, metricsItems []string, readFile ReadFileFunc) []byte {
```suggestion
func metrics(filePathDg, filePathDgReverse string, metricsItems []string, readFile ReadFileFunc) []byte {
```

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
> +			adjacencyListTemp := loadJsonFile(jsonData)
Functions like `readFile` and `loadJsonFile` must return an error instead of panicking.

2024-09-26 21:29 UTC, ekhabarov commented on cmd/metrics.go
>  	reportJson, _ := json.MarshalIndent(report, "", "  ")
Please, check an error.

2024-09-26 21:29 UTC, ekhabarov commented on cmd/root.go
> +		filePathDgReverse, _ := cmd.Flags().GetString("rdg")
Check errors please.

2024-09-28 00:26 UTC, AlexTereshenkov commented
Noted the comments, addressing in the subsequent PRs!

2024-09-28 00:26 UTC, merged